package com.memoire.model;
// Generated 27 août 2025, 15:04:07 by Hibernate Tools 6.5.1.Final

import java.sql.Date;

/**
 * ActeMedical generated by hbm2java
 */
public class ActeMedical implements java.io.Serializable {

	private int idActe;
	private Facture facture;
	private Patient patient;
	private Date date;
	private String type;

	public ActeMedical() {
	}

	public ActeMedical(Facture facture, Patient patient) {
		this.facture = facture;
		this.patient = patient;
	}

	public ActeMedical(Facture facture, Patient patient, Date date, String type) {
		this.facture = facture;
		this.patient = patient;
		this.date = date;
		this.type = type;
	}

	public int getIdActe() {
		return this.idActe;
	}

	public void setIdActe(int idActe) {
		this.idActe = idActe;
	}

	public Facture getFacture() {
		return this.facture;
	}

	public void setFacture(Facture facture) {
		this.facture = facture;
	}

	public Patient getPatient() {
		return this.patient;
	}

	public void setPatient(Patient patient) {
		this.patient = patient;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
