package com.memoire.model;
// Generated 27 août 2025, 15:04:07 by Hibernate Tools 6.5.1.Final

import java.sql.Date;

/**
 * AgentEtat generated by hbm2java
 */
public class AgentEtat extends com.memoire.model.Utilisateur implements java.io.Serializable {

	private String departement;

	public AgentEtat() {
	}

	public AgentEtat(boolean estAdmin) {
		super(estAdmin);
	}

	public AgentEtat(String nomUtilisateur, String motDePasse, String email, String telephone, String adresse,
			Date dateCreation, Date derniereConnexion, boolean estActif, String photo, boolean estAdmin,
			String departement) {
		super(nomUtilisateur, motDePasse, email, telephone, adresse, dateCreation, derniereConnexion, estActif, photo,
				estAdmin);
		this.departement = departement;
	}

	public String getDepartement() {
		return this.departement;
	}

	public void setDepartement(String departement) {
		this.departement = departement;
	}

}
