package com.memoire.model;
// Generated 27 août 2025, 15:04:07 by Hibernate Tools 6.5.1.Final

import java.sql.Date;
import java.sql.Timestamp;

/**
 * Analyse generated by hbm2java
 */
public class Analyse extends com.memoire.model.ActeMedical implements java.io.Serializable {

	private int numero;
	private String nom;
	private String description;
	private Timestamp datePrescription;
	private Timestamp dateRealisation;
	private Boolean urgence;
	private Laboratoire laboratoire;
	private Medecin medecin;
	private Patient patientAnalyse;

	public Analyse() {
	}

	public Analyse(Facture facture, Patient patient, Laboratoire laboratoire, Medecin medecin, Patient patientAnalyse) {
		super(facture, patient);
		this.laboratoire = laboratoire;
		this.medecin = medecin;
		this.patientAnalyse = patientAnalyse;
	}

	public Analyse(Facture facture, Patient patient, Date date, String type, int numero, String nom, String description,
			Timestamp datePrescription, Timestamp dateRealisation, Boolean urgence, Laboratoire laboratoire,
			Medecin medecin, Patient patientAnalyse) {
		super(facture, patient, date, type);
		this.numero = numero;
		this.nom = nom;
		this.description = description;
		this.datePrescription = datePrescription;
		this.dateRealisation = dateRealisation;
		this.urgence = urgence;
		this.laboratoire = laboratoire;
		this.medecin = medecin;
		this.patientAnalyse = patientAnalyse;
	}

	public int getNumero() {
		return this.numero;
	}

	public void setNumero(int numero) {
		this.numero = numero;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Timestamp getDatePrescription() {
		return this.datePrescription;
	}

	public void setDatePrescription(Timestamp datePrescription) {
		this.datePrescription = datePrescription;
	}

	public Timestamp getDateRealisation() {
		return this.dateRealisation;
	}

	public void setDateRealisation(Timestamp dateRealisation) {
		this.dateRealisation = dateRealisation;
	}

	public Boolean getUrgence() {
		return this.urgence;
	}

	public void setUrgence(Boolean urgence) {
		this.urgence = urgence;
	}

	public Laboratoire getLaboratoire() {
		return this.laboratoire;
	}

	public void setLaboratoire(Laboratoire laboratoire) {
		this.laboratoire = laboratoire;
	}

	public Medecin getMedecin() {
		return this.medecin;
	}

	public void setMedecin(Medecin medecin) {
		this.medecin = medecin;
	}

	public Patient getPatientAnalyse() {
		return this.patientAnalyse;
	}

	public void setPatientAnalyse(Patient patientAnalyse) {
		this.patientAnalyse = patientAnalyse;
	}

}
