package com.memoire.model;
// Generated 27 août 2025, 15:04:07 by Hibernate Tools 6.5.1.Final

/**
 * Capteur generated by hbm2java
 */
public class Capteur implements java.io.Serializable {

	private int idCapteur;
	private Patient patient;
	private String typeCapteur;
	private String modele;
	private String identifiantHardware;

	public Capteur() {
	}

	public Capteur(Patient patient) {
		this.patient = patient;
	}

	public Capteur(Patient patient, String typeCapteur, String modele, String identifiantHardware) {
		this.patient = patient;
		this.typeCapteur = typeCapteur;
		this.modele = modele;
		this.identifiantHardware = identifiantHardware;
	}

	public int getIdCapteur() {
		return this.idCapteur;
	}

	public void setIdCapteur(int idCapteur) {
		this.idCapteur = idCapteur;
	}

	public Patient getPatient() {
		return this.patient;
	}

	public void setPatient(Patient patient) {
		this.patient = patient;
	}

	public String getTypeCapteur() {
		return this.typeCapteur;
	}

	public void setTypeCapteur(String typeCapteur) {
		this.typeCapteur = typeCapteur;
	}

	public String getModele() {
		return this.modele;
	}

	public void setModele(String modele) {
		this.modele = modele;
	}

	public String getIdentifiantHardware() {
		return this.identifiantHardware;
	}

	public void setIdentifiantHardware(String identifiantHardware) {
		this.identifiantHardware = identifiantHardware;
	}

}
