package com.memoire.model;
// Generated 27 août 2025, 15:04:07 by Hibernate Tools 6.5.1.Final

import java.sql.Date;
import java.sql.Timestamp;

/**
 * Consultation generated by hbm2java
 */
public class Consultation extends com.memoire.model.ActeMedical implements java.io.Serializable {

	private Timestamp dateHeure;
	private String notesMedecin;
	private SessionVideoconference sessionVideoconference;
	private RendezVous rendezVous;
	private Medecin medecinConsultation;

	public Consultation() {
	}

	public Consultation(Facture facture, Patient patient) {
		super(facture, patient);
	}

	public Consultation(Facture facture, Patient patient, Date date, String type, Timestamp dateHeure,
			String notesMedecin, SessionVideoconference sessionVideoconference, RendezVous rendezVous,
			Medecin medecinConsultation) {
		super(facture, patient, date, type);
		this.dateHeure = dateHeure;
		this.notesMedecin = notesMedecin;
		this.sessionVideoconference = sessionVideoconference;
		this.rendezVous = rendezVous;
		this.medecinConsultation = medecinConsultation;
	}

	public Timestamp getDateHeure() {
		return this.dateHeure;
	}

	public void setDateHeure(Timestamp dateHeure) {
		this.dateHeure = dateHeure;
	}

	public String getNotesMedecin() {
		return this.notesMedecin;
	}

	public void setNotesMedecin(String notesMedecin) {
		this.notesMedecin = notesMedecin;
	}

	public SessionVideoconference getSessionVideoconference() {
		return this.sessionVideoconference;
	}

	public void setSessionVideoconference(SessionVideoconference sessionVideoconference) {
		this.sessionVideoconference = sessionVideoconference;
	}

	public RendezVous getRendezVous() {
		return this.rendezVous;
	}

	public void setRendezVous(RendezVous rendezVous) {
		this.rendezVous = rendezVous;
	}

	public Medecin getMedecinConsultation() {
		return this.medecinConsultation;
	}

	public void setMedecinConsultation(Medecin medecinConsultation) {
		this.medecinConsultation = medecinConsultation;
	}

}
