package com.memoire.model;
// Generated 27 août 2025, 15:04:07 by Hibernate Tools 6.5.1.Final

/**
 * ContactPatient generated by hbm2java
 */
public class ContactPatient implements java.io.Serializable {

	private int contactId;
	private int patientId;

	public ContactPatient() {
	}

	public ContactPatient(int contactId, int patientId) {
		this.contactId = contactId;
		this.patientId = patientId;
	}

	public int getContactId() {
		return this.contactId;
	}

	public void setContactId(int contactId) {
		this.contactId = contactId;
	}

	public int getPatientId() {
		return this.patientId;
	}

	public void setPatientId(int patientId) {
		this.patientId = patientId;
	}

}
