package com.memoire.model;
// Generated 27 août 2025, 15:04:07 by Hibernate Tools 6.5.1.Final

import java.sql.Date;

/**
 * Contact generated by hbm2java
 */
public class Contact extends com.memoire.model.Utilisateur implements java.io.Serializable {

	public Contact() {
	}

	public Contact(boolean estAdmin) {
		super(estAdmin);
	}

	public Contact(String nomUtilisateur, String motDePasse, String email, String telephone, String adresse,
			Date dateCreation, Date derniereConnexion, boolean estActif, String photo, boolean estAdmin) {
		super(nomUtilisateur, motDePasse, email, telephone, adresse, dateCreation, derniereConnexion, estActif, photo,
				estAdmin);
	}

}
