package com.memoire.model;
// Generated 27 août 2025, 15:04:07 by Hibernate Tools 6.5.1.Final

/**
 * DetailPrescription generated by hbm2java
 */
public class DetailPrescription implements java.io.Serializable {

	private int idDetail;
	private Prescription prescription;
	private String libelle;
	private String produit;
	private int quantite;

	public DetailPrescription() {
	}

	public DetailPrescription(Prescription prescription) {
		this.prescription = prescription;
	}

	public DetailPrescription(Prescription prescription, String libelle, String produit, int quantite) {
		this.prescription = prescription;
		this.libelle = libelle;
		this.produit = produit;
		this.quantite = quantite;
	}

	public int getIdDetail() {
		return this.idDetail;
	}

	public void setIdDetail(int idDetail) {
		this.idDetail = idDetail;
	}

	public Prescription getPrescription() {
		return this.prescription;
	}

	public void setPrescription(Prescription prescription) {
		this.prescription = prescription;
	}

	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	public String getProduit() {
		return this.produit;
	}

	public void setProduit(String produit) {
		this.produit = produit;
	}

	public int getQuantite() {
		return this.quantite;
	}

	public void setQuantite(int quantite) {
		this.quantite = quantite;
	}

}
