package com.memoire.model;
// Generated 27 août 2025, 15:04:07 by Hibernate Tools 6.5.1.Final

/**
 * Domaine generated by hbm2java
 */
public class Domaine implements java.io.Serializable {

	private int idDomaine;
	private String famille;

	public Domaine() {
	}

	public Domaine(String famille) {
		this.famille = famille;
	}

	public int getIdDomaine() {
		return this.idDomaine;
	}

	public void setIdDomaine(int idDomaine) {
		this.idDomaine = idDomaine;
	}

	public String getFamille() {
		return this.famille;
	}

	public void setFamille(String famille) {
		this.famille = famille;
	}

}
