package com.memoire.model;
// Generated 27 août 2025, 15:04:07 by Hibernate Tools 6.5.1.Final

import java.math.BigDecimal;
import java.sql.Date;

/**
 * DonneeCapteur generated by hbm2java
 */
public class DonneeCapteur implements java.io.Serializable {

	private int id;
	private Capteur capteur;
	private BigDecimal valeur;
	private Date dateReception;

	public DonneeCapteur() {
	}

	public DonneeCapteur(Capteur capteur) {
		this.capteur = capteur;
	}

	public DonneeCapteur(Capteur capteur, BigDecimal valeur, Date dateReception) {
		this.capteur = capteur;
		this.valeur = valeur;
		this.dateReception = dateReception;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Capteur getCapteur() {
		return this.capteur;
	}

	public void setCapteur(Capteur capteur) {
		this.capteur = capteur;
	}

	public BigDecimal getValeur() {
		return this.valeur;
	}

	public void setValeur(BigDecimal valeur) {
		this.valeur = valeur;
	}

	public Date getDateReception() {
		return this.dateReception;
	}

	public void setDateReception(Date dateReception) {
		this.dateReception = dateReception;
	}

}
