package com.memoire.model;
// Generated 27 août 2025, 15:04:07 by Hibernate Tools 6.5.1.Final

import java.sql.Date;

/**
 * Facture generated by hbm2java
 */
public class Facture implements java.io.Serializable {

	private int idFacture;
	private int montant;
	private String statut;
	private Date dateEmission;

	public Facture() {
	}

	public Facture(int montant, String statut, Date dateEmission) {
		this.montant = montant;
		this.statut = statut;
		this.dateEmission = dateEmission;
	}

	public int getIdFacture() {
		return this.idFacture;
	}

	public void setIdFacture(int idFacture) {
		this.idFacture = idFacture;
	}

	public int getMontant() {
		return this.montant;
	}

	public void setMontant(int montant) {
		this.montant = montant;
	}

	public String getStatut() {
		return this.statut;
	}

	public void setStatut(String statut) {
		this.statut = statut;
	}

	public Date getDateEmission() {
		return this.dateEmission;
	}

	public void setDateEmission(Date dateEmission) {
		this.dateEmission = dateEmission;
	}

}
