package com.memoire.model;
// Generated 27 août 2025, 15:04:07 by Hibernate Tools 6.5.1.Final

import java.sql.Date;

/**
 * Fichier generated by hbm2java
 */
public class Fichier implements java.io.Serializable {

	private int idFichier;
	private String nomFichier;
	private String urlFichier;
	private String typeFichier;
	private Date dateUpload;

	public Fichier() {
	}

	public Fichier(String nomFichier, String urlFichier, String typeFichier, Date dateUpload) {
		this.nomFichier = nomFichier;
		this.urlFichier = urlFichier;
		this.typeFichier = typeFichier;
		this.dateUpload = dateUpload;
	}

	public int getIdFichier() {
		return this.idFichier;
	}

	public void setIdFichier(int idFichier) {
		this.idFichier = idFichier;
	}

	public String getNomFichier() {
		return this.nomFichier;
	}

	public void setNomFichier(String nomFichier) {
		this.nomFichier = nomFichier;
	}

	public String getUrlFichier() {
		return this.urlFichier;
	}

	public void setUrlFichier(String urlFichier) {
		this.urlFichier = urlFichier;
	}

	public String getTypeFichier() {
		return this.typeFichier;
	}

	public void setTypeFichier(String typeFichier) {
		this.typeFichier = typeFichier;
	}

	public Date getDateUpload() {
		return this.dateUpload;
	}

	public void setDateUpload(Date dateUpload) {
		this.dateUpload = dateUpload;
	}

}
