package com.memoire.model;
// Generated 27 août 2025, 15:04:07 by Hibernate Tools 6.5.1.Final

/**
 * Laboratoire generated by hbm2java
 */
public class Laboratoire implements java.io.Serializable {

	private int idLaboratoire;
	private StructureSanitaire structureSanitaire;
	private int fixe;
	private String localisationGPS;
	private String siteWeb;

	public Laboratoire() {
	}

	public Laboratoire(StructureSanitaire structureSanitaire, int fixe, String localisationGPS, String siteWeb) {
		this.structureSanitaire = structureSanitaire;
		this.fixe = fixe;
		this.localisationGPS = localisationGPS;
		this.siteWeb = siteWeb;
	}

	public int getIdLaboratoire() {
		return this.idLaboratoire;
	}

	public void setIdLaboratoire(int idLaboratoire) {
		this.idLaboratoire = idLaboratoire;
	}

	public StructureSanitaire getStructureSanitaire() {
		return this.structureSanitaire;
	}

	public void setStructureSanitaire(StructureSanitaire structureSanitaire) {
		this.structureSanitaire = structureSanitaire;
	}

	public int getFixe() {
		return this.fixe;
	}

	public void setFixe(int fixe) {
		this.fixe = fixe;
	}

	public String getLocalisationGPS() {
		return this.localisationGPS;
	}

	public void setLocalisationGPS(String localisationGPS) {
		this.localisationGPS = localisationGPS;
	}

	public String getSiteWeb() {
		return this.siteWeb;
	}

	public void setSiteWeb(String siteWeb) {
		this.siteWeb = siteWeb;
	}

}
