package com.memoire.model;
// Generated 27 août 2025, 15:04:07 by Hibernate Tools 6.5.1.Final

import java.sql.Date;

/**
 * Medecin generated by hbm2java
 */
public class Medecin extends com.memoire.model.Utilisateur implements java.io.Serializable {

	private int numeroLicence;
	private StructureSanitaire structureSanitaire;

	public Medecin() {
	}

	public Medecin(boolean estAdmin) {
		super(estAdmin);
	}

	public Medecin(String nomUtilisateur, String motDePasse, String email, String telephone, String adresse,
			Date dateCreation, Date derniereConnexion, boolean estActif, String photo, boolean estAdmin,
			int numeroLicence, StructureSanitaire structureSanitaire) {
		super(nomUtilisateur, motDePasse, email, telephone, adresse, dateCreation, derniereConnexion, estActif, photo,
				estAdmin);
		this.numeroLicence = numeroLicence;
		this.structureSanitaire = structureSanitaire;
	}

	public int getNumeroLicence() {
		return this.numeroLicence;
	}

	public void setNumeroLicence(int numeroLicence) {
		this.numeroLicence = numeroLicence;
	}

	public StructureSanitaire getStructureSanitaire() {
		return this.structureSanitaire;
	}

	public void setStructureSanitaire(StructureSanitaire structureSanitaire) {
		this.structureSanitaire = structureSanitaire;
	}

}
