package com.memoire.model;
// Generated 27 août 2025, 15:04:07 by Hibernate Tools 6.5.1.Final

/**
 * MessageChat generated by hbm2java
 */
public class MessageChat implements java.io.Serializable {

	private int idMessage;
	private Medecin medecin;
	private Patient patient;
	private String message;
	private boolean estLu;

	public MessageChat() {
	}

	public MessageChat(Medecin medecin, Patient patient) {
		this.medecin = medecin;
		this.patient = patient;
	}

	public MessageChat(Medecin medecin, Patient patient, String message, boolean estLu) {
		this.medecin = medecin;
		this.patient = patient;
		this.message = message;
		this.estLu = estLu;
	}

	public int getIdMessage() {
		return this.idMessage;
	}

	public void setIdMessage(int idMessage) {
		this.idMessage = idMessage;
	}

	public Medecin getMedecin() {
		return this.medecin;
	}

	public void setMedecin(Medecin medecin) {
		this.medecin = medecin;
	}

	public Patient getPatient() {
		return this.patient;
	}

	public void setPatient(Patient patient) {
		this.patient = patient;
	}

	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public boolean isEstLu() {
		return this.estLu;
	}

	public void setEstLu(boolean estLu) {
		this.estLu = estLu;
	}

}
