package com.memoire.model;
// Generated 27 août 2025, 15:04:07 by Hibernate Tools 6.5.1.Final

/**
 * Nature generated by hbm2java
 */
public class Nature implements java.io.Serializable {

	private int idNature;
	private String libelle;
	private int nombre;

	public Nature() {
	}

	public Nature(String libelle, int nombre) {
		this.libelle = libelle;
		this.nombre = nombre;
	}

	public int getIdNature() {
		return this.idNature;
	}

	public void setIdNature(int idNature) {
		this.idNature = idNature;
	}

	public String getLibelle() {
		return this.libelle;
	}

	public void setLibelle(String libelle) {
		this.libelle = libelle;
	}

	public int getNombre() {
		return this.nombre;
	}

	public void setNombre(int nombre) {
		this.nombre = nombre;
	}

}
