package com.memoire.model;
// Generated 27 août 2025, 15:04:07 by Hibernate Tools 6.5.1.Final

/**
 * NecessiteDetail generated by hbm2java
 */
public class NecessiteDetail implements java.io.Serializable {

	private int idDetail;
	private int idNecessite;

	public NecessiteDetail() {
	}

	public NecessiteDetail(int idDetail, int idNecessite) {
		this.idDetail = idDetail;
		this.idNecessite = idNecessite;
	}

	public int getIdDetail() {
		return this.idDetail;
	}

	public void setIdDetail(int idDetail) {
		this.idDetail = idDetail;
	}

	public int getIdNecessite() {
		return this.idNecessite;
	}

	public void setIdNecessite(int idNecessite) {
		this.idNecessite = idNecessite;
	}

}
