package com.memoire.model;
// Generated 27 août 2025, 15:04:07 by Hibernate Tools 6.5.1.Final

/**
 * Necessite generated by hbm2java
 */
public class Necessite implements java.io.Serializable {

	private int idNecessite;
	private String note;

	public Necessite() {
	}

	public Necessite(String note) {
		this.note = note;
	}

	public int getIdNecessite() {
		return this.idNecessite;
	}

	public void setIdNecessite(int idNecessite) {
		this.idNecessite = idNecessite;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}
