package com.memoire.model;
// Generated 27 août 2025, 15:04:07 by Hibernate Tools 6.5.1.Final

/**
 * Notification generated by hbm2java
 */
public class Notification implements java.io.Serializable {

	private int idNotification;
	private Utilisateur utilisateur;
	private String type;
	private String contenu;
	private String dateEnvoi;
	private boolean estVisible;

	public Notification() {
	}

	public Notification(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	public Notification(Utilisateur utilisateur, String type, String contenu, String dateEnvoi, boolean estVisible) {
		this.utilisateur = utilisateur;
		this.type = type;
		this.contenu = contenu;
		this.dateEnvoi = dateEnvoi;
		this.estVisible = estVisible;
	}

	public int getIdNotification() {
		return this.idNotification;
	}

	public void setIdNotification(int idNotification) {
		this.idNotification = idNotification;
	}

	public Utilisateur getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(Utilisateur utilisateur) {
		this.utilisateur = utilisateur;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getContenu() {
		return this.contenu;
	}

	public void setContenu(String contenu) {
		this.contenu = contenu;
	}

	public String getDateEnvoi() {
		return this.dateEnvoi;
	}

	public void setDateEnvoi(String dateEnvoi) {
		this.dateEnvoi = dateEnvoi;
	}

	public boolean isEstVisible() {
		return this.estVisible;
	}

	public void setEstVisible(boolean estVisible) {
		this.estVisible = estVisible;
	}

}
