package com.memoire.model;
// Generated 27 août 2025, 15:04:07 by Hibernate Tools 6.5.1.Final

import java.sql.Date;

/**
 * Patient generated by hbm2java
 */
public class Patient extends com.memoire.model.Utilisateur implements java.io.Serializable {

	private java.util.Date dateNaissance;

	public Patient() {
	}

	public Patient(boolean estAdmin) {
		super(estAdmin);
	}

	public Patient(String nomUtilisateur, String motDePasse, String email, String telephone, String adresse,
			Date dateCreation, Date derniereConnexion, boolean estActif, String photo, boolean estAdmin,
			java.util.Date dateNaissance) {
		super(nomUtilisateur, motDePasse, email, telephone, adresse, dateCreation, derniereConnexion, estActif, photo,
				estAdmin);
		this.dateNaissance = dateNaissance;
	}

	public java.util.Date getDateNaissance() {
		return this.dateNaissance;
	}

	public void setDateNaissance(java.util.Date dateNaissance) {
		this.dateNaissance = dateNaissance;
	}

}
