package com.memoire.model;
// Generated 27 août 2025, 15:04:07 by Hibernate Tools 6.5.1.Final

/**
 * Permission generated by hbm2java
 */
public class Permission implements java.io.Serializable {

	private int idPermission;
	private int codePermission;
	private String nom;
	private String description;

	public Permission() {
	}

	public Permission(int codePermission, String nom, String description) {
		this.codePermission = codePermission;
		this.nom = nom;
		this.description = description;
	}

	public int getIdPermission() {
		return this.idPermission;
	}

	public void setIdPermission(int idPermission) {
		this.idPermission = idPermission;
	}

	public int getCodePermission() {
		return this.codePermission;
	}

	public void setCodePermission(int codePermission) {
		this.codePermission = codePermission;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
