package com.memoire.model;
// Generated 27 août 2025, 15:04:07 by Hibernate Tools 6.5.1.Final

/**
 * Prescription generated by hbm2java
 */
public class Prescription implements java.io.Serializable {

	private int idPrescription;
	private Consultation consultation;
	private String type;
	private String analyse;

	public Prescription() {
	}

	public Prescription(Consultation consultation) {
		this.consultation = consultation;
	}

	public Prescription(Consultation consultation, String type, String analyse) {
		this.consultation = consultation;
		this.type = type;
		this.analyse = analyse;
	}

	public int getIdPrescription() {
		return this.idPrescription;
	}

	public void setIdPrescription(int idPrescription) {
		this.idPrescription = idPrescription;
	}

	public Consultation getConsultation() {
		return this.consultation;
	}

	public void setConsultation(Consultation consultation) {
		this.consultation = consultation;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getAnalyse() {
		return this.analyse;
	}

	public void setAnalyse(String analyse) {
		this.analyse = analyse;
	}

}
