package com.memoire.model;
// Generated 27 août 2025, 15:04:07 by Hibernate Tools 6.5.1.Final

import java.sql.Date;

/**
 * RendezVous generated by hbm2java
 */
public class RendezVous implements java.io.Serializable {

	private int idRendezVous;
	private Medecin medecin;
	private Patient patient;
	private Date dateHeure;
	private String statut;
	private String motif;

	public RendezVous() {
	}

	public RendezVous(Medecin medecin, Patient patient) {
		this.medecin = medecin;
		this.patient = patient;
	}

	public RendezVous(Medecin medecin, Patient patient, Date dateHeure, String statut, String motif) {
		this.medecin = medecin;
		this.patient = patient;
		this.dateHeure = dateHeure;
		this.statut = statut;
		this.motif = motif;
	}

	public int getIdRendezVous() {
		return this.idRendezVous;
	}

	public void setIdRendezVous(int idRendezVous) {
		this.idRendezVous = idRendezVous;
	}

	public Medecin getMedecin() {
		return this.medecin;
	}

	public void setMedecin(Medecin medecin) {
		this.medecin = medecin;
	}

	public Patient getPatient() {
		return this.patient;
	}

	public void setPatient(Patient patient) {
		this.patient = patient;
	}

	public Date getDateHeure() {
		return this.dateHeure;
	}

	public void setDateHeure(Date dateHeure) {
		this.dateHeure = dateHeure;
	}

	public String getStatut() {
		return this.statut;
	}

	public void setStatut(String statut) {
		this.statut = statut;
	}

	public String getMotif() {
		return this.motif;
	}

	public void setMotif(String motif) {
		this.motif = motif;
	}

}
