package com.memoire.model;
// Generated 27 août 2025, 15:04:07 by Hibernate Tools 6.5.1.Final

/**
 * ResultatAnalyse generated by hbm2java
 */
public class ResultatAnalyse implements java.io.Serializable {

	private int idResultat;
	private Fichier fichier;
	private Analyse analyse;
	private String interpretation;

	public ResultatAnalyse() {
	}

	public ResultatAnalyse(Fichier fichier, Analyse analyse) {
		this.fichier = fichier;
		this.analyse = analyse;
	}

	public ResultatAnalyse(Fichier fichier, Analyse analyse, String interpretation) {
		this.fichier = fichier;
		this.analyse = analyse;
		this.interpretation = interpretation;
	}

	public int getIdResultat() {
		return this.idResultat;
	}

	public void setIdResultat(int idResultat) {
		this.idResultat = idResultat;
	}

	public Fichier getFichier() {
		return this.fichier;
	}

	public void setFichier(Fichier fichier) {
		this.fichier = fichier;
	}

	public Analyse getAnalyse() {
		return this.analyse;
	}

	public void setAnalyse(Analyse analyse) {
		this.analyse = analyse;
	}

	public String getInterpretation() {
		return this.interpretation;
	}

	public void setInterpretation(String interpretation) {
		this.interpretation = interpretation;
	}

}
