package com.memoire.model;
// Generated 27 août 2025, 15:04:07 by Hibernate Tools 6.5.1.Final

/**
 * Role generated by hbm2java
 */
public class Role implements java.io.Serializable {

	private int idPermission;
	private int idUtilisateur;
	private String date;

	public Role() {
	}

	public Role(int idPermission, int idUtilisateur) {
		this.idPermission = idPermission;
		this.idUtilisateur = idUtilisateur;
	}

	public Role(int idPermission, int idUtilisateur, String date) {
		this.idPermission = idPermission;
		this.idUtilisateur = idUtilisateur;
		this.date = date;
	}

	public int getIdPermission() {
		return this.idPermission;
	}

	public void setIdPermission(int idPermission) {
		this.idPermission = idPermission;
	}

	public int getIdUtilisateur() {
		return this.idUtilisateur;
	}

	public void setIdUtilisateur(int idUtilisateur) {
		this.idUtilisateur = idUtilisateur;
	}

	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

}
