package com.memoire.model;
// Generated 27 août 2025, 15:04:07 by Hibernate Tools 6.5.1.Final

/**
 * Service generated by hbm2java
 */
public class Service implements java.io.Serializable {

	private int idService;
	private String nom;
	private String description;
	private boolean disponible;

	public Service() {
	}

	public Service(String nom, String description, boolean disponible) {
		this.nom = nom;
		this.description = description;
		this.disponible = disponible;
	}

	public int getIdService() {
		return this.idService;
	}

	public void setIdService(int idService) {
		this.idService = idService;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public boolean isDisponible() {
		return this.disponible;
	}

	public void setDisponible(boolean disponible) {
		this.disponible = disponible;
	}

}
