package com.memoire.model;
// Generated 27 août 2025, 15:04:07 by Hibernate Tools 6.5.1.Final

/**
 * ServiceStructure generated by hbm2java
 */
public class ServiceStructure implements java.io.Serializable {

	private int idService;
	private int idStructure;

	public ServiceStructure() {
	}

	public ServiceStructure(int idService, int idStructure) {
		this.idService = idService;
		this.idStructure = idStructure;
	}

	public int getIdService() {
		return this.idService;
	}

	public void setIdService(int idService) {
		this.idService = idService;
	}

	public int getIdStructure() {
		return this.idStructure;
	}

	public void setIdStructure(int idStructure) {
		this.idStructure = idStructure;
	}

}
