package com.memoire.model;
// Generated 27 août 2025, 15:04:07 by Hibernate Tools 6.5.1.Final

import java.sql.Date;

/**
 * SessionVideoconference generated by hbm2java
 */
public class SessionVideoconference implements java.io.Serializable {

	private int idSession;
	private String urlSession;
	private Date heureDebut;
	private Date heureFin;
	private String statutSession;

	public SessionVideoconference() {
	}

	public SessionVideoconference(String urlSession) {
		this.urlSession = urlSession;
	}

	public SessionVideoconference(String urlSession, Date heureDebut, Date heureFin, String statutSession) {
		this.urlSession = urlSession;
		this.heureDebut = heureDebut;
		this.heureFin = heureFin;
		this.statutSession = statutSession;
	}

	public int getIdSession() {
		return this.idSession;
	}

	public void setIdSession(int idSession) {
		this.idSession = idSession;
	}

	public String getUrlSession() {
		return this.urlSession;
	}

	public void setUrlSession(String urlSession) {
		this.urlSession = urlSession;
	}

	public Date getHeureDebut() {
		return this.heureDebut;
	}

	public void setHeureDebut(Date heureDebut) {
		this.heureDebut = heureDebut;
	}

	public Date getHeureFin() {
		return this.heureFin;
	}

	public void setHeureFin(Date heureFin) {
		this.heureFin = heureFin;
	}

	public String getStatutSession() {
		return this.statutSession;
	}

	public void setStatutSession(String statutSession) {
		this.statutSession = statutSession;
	}

}
