package com.memoire.model;
// Generated 27 août 2025, 15:04:07 by Hibernate Tools 6.5.1.Final

/**
 * SpecialiteMedecin generated by hbm2java
 */
public class SpecialiteMedecin implements java.io.Serializable {

	private int idSpecilite;
	private int idUtilisateur;

	public SpecialiteMedecin() {
	}

	public SpecialiteMedecin(int idSpecilite, int idUtilisateur) {
		this.idSpecilite = idSpecilite;
		this.idUtilisateur = idUtilisateur;
	}

	public int getIdSpecilite() {
		return this.idSpecilite;
	}

	public void setIdSpecilite(int idSpecilite) {
		this.idSpecilite = idSpecilite;
	}

	public int getIdUtilisateur() {
		return this.idUtilisateur;
	}

	public void setIdUtilisateur(int idUtilisateur) {
		this.idUtilisateur = idUtilisateur;
	}

}
