package com.memoire.model;
// Generated 27 août 2025, 15:04:07 by Hibernate Tools 6.5.1.Final

/**
 * Specialite generated by hbm2java
 */
public class Specialite implements java.io.Serializable {

	private int idSpecilite;
	private Domaine domaine;
	private String nom;

	public Specialite() {
	}

	public Specialite(Domaine domaine) {
		this.domaine = domaine;
	}

	public Specialite(Domaine domaine, String nom) {
		this.domaine = domaine;
		this.nom = nom;
	}

	public int getIdSpecilite() {
		return this.idSpecilite;
	}

	public void setIdSpecilite(int idSpecilite) {
		this.idSpecilite = idSpecilite;
	}

	public Domaine getDomaine() {
		return this.domaine;
	}

	public void setDomaine(Domaine domaine) {
		this.domaine = domaine;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

}
