package com.memoire.model;
// Generated 27 août 2025, 15:04:07 by Hibernate Tools 6.5.1.Final

/**
 * StructureSanitaire generated by hbm2java
 */
public class StructureSanitaire implements java.io.Serializable {

	private int idStructure;
	private Nature nature;
	private AgentEtat agentEtat;
	private String nom;
	private String adresse;
	private long telephone;
	private String email;

	public StructureSanitaire() {
	}

	public StructureSanitaire(Nature nature, AgentEtat agentEtat) {
		this.nature = nature;
		this.agentEtat = agentEtat;
	}

	public StructureSanitaire(Nature nature, AgentEtat agentEtat, String nom, String adresse, long telephone,
			String email) {
		this.nature = nature;
		this.agentEtat = agentEtat;
		this.nom = nom;
		this.adresse = adresse;
		this.telephone = telephone;
		this.email = email;
	}

	public int getIdStructure() {
		return this.idStructure;
	}

	public void setIdStructure(int idStructure) {
		this.idStructure = idStructure;
	}

	public Nature getNature() {
		return this.nature;
	}

	public void setNature(Nature nature) {
		this.nature = nature;
	}

	public AgentEtat getAgentEtat() {
		return this.agentEtat;
	}

	public void setAgentEtat(AgentEtat agentEtat) {
		this.agentEtat = agentEtat;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	public long getTelephone() {
		return this.telephone;
	}

	public void setTelephone(long telephone) {
		this.telephone = telephone;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}
