package com.memoire.model;
// Generated 27 août 2025, 15:04:07 by Hibernate Tools 6.5.1.Final

/**
 * Type generated by hbm2java
 */
public class Type implements java.io.Serializable {

	private int idType;
	private StructureSanitaire structureSanitaire;
	private boolean estPublic;
	private int nbrePrive;
	private int nbrePublic;

	public Type() {
	}

	public Type(StructureSanitaire structureSanitaire, boolean estPublic, int nbrePrive, int nbrePublic) {
		this.structureSanitaire = structureSanitaire;
		this.estPublic = estPublic;
		this.nbrePrive = nbrePrive;
		this.nbrePublic = nbrePublic;
	}

	public int getIdType() {
		return this.idType;
	}

	public void setIdType(int idType) {
		this.idType = idType;
	}

	public StructureSanitaire getStructureSanitaire() {
		return this.structureSanitaire;
	}

	public void setStructureSanitaire(StructureSanitaire structureSanitaire) {
		this.structureSanitaire = structureSanitaire;
	}

	public boolean isEstPublic() {
		return this.estPublic;
	}

	public void setEstPublic(boolean estPublic) {
		this.estPublic = estPublic;
	}

	public int getNbrePrive() {
		return this.nbrePrive;
	}

	public void setNbrePrive(int nbrePrive) {
		this.nbrePrive = nbrePrive;
	}

	public int getNbrePublic() {
		return this.nbrePublic;
	}

	public void setNbrePublic(int nbrePublic) {
		this.nbrePublic = nbrePublic;
	}

}
