package com.memoire.model;
// Generated 27 août 2025, 15:04:07 by Hibernate Tools 6.5.1.Final

import java.sql.Date;

/**
 * Utilisateur generated by hbm2java
 */
public class Utilisateur implements java.io.Serializable {

	private int idUtilisateur;
	private String nomUtilisateur;
	private String motDePasse;
	private String email;
	private String telephone;
	private String adresse;
	private Date dateCreation;
	private Date derniereConnexion;
	private boolean estActif;
	private String photo;
	private boolean estAdmin;

	public Utilisateur() {
	}

	public Utilisateur(boolean estAdmin) {
		this.estAdmin = estAdmin;
	}

	public Utilisateur(String nomUtilisateur, String motDePasse, String email, String telephone, String adresse,
			Date dateCreation, Date derniereConnexion, boolean estActif, String photo, boolean estAdmin) {
		this.nomUtilisateur = nomUtilisateur;
		this.motDePasse = motDePasse;
		this.email = email;
		this.telephone = telephone;
		this.adresse = adresse;
		this.dateCreation = dateCreation;
		this.derniereConnexion = derniereConnexion;
		this.estActif = estActif;
		this.photo = photo;
		this.estAdmin = estAdmin;
	}

	public int getIdUtilisateur() {
		return this.idUtilisateur;
	}

	public void setIdUtilisateur(int idUtilisateur) {
		this.idUtilisateur = idUtilisateur;
	}

	public String getNomUtilisateur() {
		return this.nomUtilisateur;
	}

	public void setNomUtilisateur(String nomUtilisateur) {
		this.nomUtilisateur = nomUtilisateur;
	}

	public String getMotDePasse() {
		return this.motDePasse;
	}

	public void setMotDePasse(String motDePasse) {
		this.motDePasse = motDePasse;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	public Date getDateCreation() {
		return this.dateCreation;
	}

	public void setDateCreation(Date dateCreation) {
		this.dateCreation = dateCreation;
	}

	public Date getDerniereConnexion() {
		return this.derniereConnexion;
	}

	public void setDerniereConnexion(Date derniereConnexion) {
		this.derniereConnexion = derniereConnexion;
	}

	public boolean isEstActif() {
		return this.estActif;
	}

	public void setEstActif(boolean estActif) {
		this.estActif = estActif;
	}

	public String getPhoto() {
		return this.photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	public boolean isEstAdmin() {
		return this.estAdmin;
	}

	public void setEstAdmin(boolean estAdmin) {
		this.estAdmin = estAdmin;
	}

}
